
class Snapshot:
    @property
    def serialized_bytes(self) -> bytes:
        ...
        # TODO: implement...

    @property
    def serialization_version(self) -> str:
        ...
        # TODO: implement...
