site_name: Bridgic
site_description: Bridge logic and magic together with autonomous AI capabilities
site_url: https://docs.bridgic.ai
repo_url: https://github.com/bitsky-tech/bridgic
repo_name: bitsky-tech/bridgic
edit_uri: edit/main/docs/docs/

nav:

  - Home: index.md
  - Getting Started:
    - Concepts: home/concepts.md
    - Installation: home/installation.md
    - Quick Start: home/quick_start.md
    - Examples: home/examples.md
  - API Reference:
      - Index: reference/bridgic-core/index.md
      - Bridgic-Core:
        - Bridgic:
          - Core:
            - Automa:
              - Arguments Descriptor: reference/bridgic-core/bridgic/core/automa/arguments_descriptor.md
              - Automa: reference/bridgic-core/bridgic/core/automa/automa.md
              - Concurrent Automa: reference/bridgic-core/bridgic/core/automa/concurrent_automa.md
              - Graph Automa: reference/bridgic-core/bridgic/core/automa/graph_automa.md
              - Interaction:
                - Event Handling: reference/bridgic-core/bridgic/core/automa/interaction/event_handling.md
                - Human Interaction: reference/bridgic-core/bridgic/core/automa/interaction/human_interaction.md
              - Sequential Automa: reference/bridgic-core/bridgic/core/automa/sequential_automa.md
              - Serialization: reference/bridgic-core/bridgic/core/automa/serialization.md
              - Worker:
                - Callable Worker: reference/bridgic-core/bridgic/core/automa/worker/callable_worker.md
                - Worker: reference/bridgic-core/bridgic/core/automa/worker/worker.md
              - Worker Decorator: reference/bridgic-core/bridgic/core/automa/worker_decorator.md
            - Intelligence:
              - Base LLM: reference/bridgic-core/bridgic/core/intelligence/base_llm.md
              - Content: reference/bridgic-core/bridgic/core/intelligence/content.md
              - Protocol: reference/bridgic-core/bridgic/core/intelligence/protocol.md
            - Prompt:
              - Base Template: reference/bridgic-core/bridgic/core/prompt/base_template.md
              - Ejinja Template: reference/bridgic-core/bridgic/core/prompt/ejinja_template.md
              - Fstring Template: reference/bridgic-core/bridgic/core/prompt/fstring_template.md
            - Types:
              - Common: reference/bridgic-core/bridgic/core/types/common.md
              - Error: reference/bridgic-core/bridgic/core/types/error.md
              - Serialization: reference/bridgic-core/bridgic/core/types/serialization.md
            - Utils:
              - Args Map: reference/bridgic-core/bridgic/core/utils/args_map.md
              - Cache: reference/bridgic-core/bridgic/core/utils/cache.md
              - Collection: reference/bridgic-core/bridgic/core/utils/collection.md
              - Console: reference/bridgic-core/bridgic/core/utils/console.md
              - Inspect Tools: reference/bridgic-core/bridgic/core/utils/inspect_tools.md
              - Msgpackx: reference/bridgic-core/bridgic/core/utils/msgpackx.md

  - About: about/index.md

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.tracking
    # Table of contents
    - toc.follow
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Content
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
  palette:
    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/bridge
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
plugins: 
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
      repository: bitsky-tech/bridgic
      branch: main
      enabled: !ENV [ENABLE_GIT_COMMITTERS, false]
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - mkdocs-jupyter:
      execute: false
      include_source: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_style: numpy
            extensions:
              - griffe_fieldz
            filters:
              - "!^_"
              - "!^__init__"
            members_order: source
            merge_init_into_class: false
            separate_signature: true
            show_root_full_path: true
            show_root_heading: false
            show_root_toc_entry: false
            show_signature_annotations: true
            signature_crossrefs: true
          paths: 
            - ../bridgic-core

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/bitsky-tech/bridgic
    # - icon: fontawesome/brands/python
    #   link: https://pypi.org/project/bridgic/
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/bridgic
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/polyfill.min.js
  - javascripts/tex-mml-chtml.js
